### ISSUE TITLE
LEGO/HHD swap option

### ISSUE THREAD

**Issue by chrishudson918** [victor-borges/handheld-controller-glyphs#11]
HHD has an option on the Legion Go to swap the "Legion R" button with "Menu"/"Start"  and "Legion L" with "View"/"Select". Would it be possible to have a secondary LEGO theme with this in mind? 
I made a fork of this theme and attempted it myself but I clearly don't know exactly what I'm doing. I'm getting the missing image icon.

My attempt: https://github.com/chrishudson918/handheld-controller-glyphs

Thanks!

**Comment by victor-borges** [comment]
I'll give it a try, making a new theme would work but then it would imply doing the same for every handheld supported, and for every setting that changes glyphs

**Comment by chrishudson918** [comment]
I must have been manually placing my fork in the wrong location or something. If I change the GitHub url in the install.sh from your release to my fork everything installs properly. 

I would imagine there are other Legion Go owners in the same boat as me. Feel free to include my Legion Go Swap theme in your next release if you'd like. Thanks buddy! :)

**Comment by victor-borges** [comment]
it's nice that you got it working!
I wasn't saying it's a big ask, but that I think there's a better way of allowing the user to configure the theme with some UI options using CSS Loader components, instead of duplicating the theme, I'm seeing if it's something that is actually possible

**Comment by chrishudson918** [comment]
Ohh I see what you're saying! That makes sense and seems like a better approach.

**Comment by chrishudson918** [comment]
I just tried the change you made. The toggle for Legion Go is great. Looks like the wrong icon got used though. The change that HHD applies makes the button with the hamburger icon the menu button.

**Comment by victor-borges** [comment]
Oh damn

**Comment by victor-borges** [comment]
Should be OK now!

**Comment by chrishudson918** [comment]
Sweet! I'll give it a try after work today.
