### ISSUE TITLE
[Bazzite] GPU Clock setting disappearing when theme is installed

### ISSUE THREAD

**Issue by SeeDborg** [victor-borges/handheld-controller-glyphs#14]
Hi,
I love your theme but I have a problem (I'm on Legion Go, Bazzite, fresh install) : when the theme is enabled, the option to set GPU Clock is disappearing of Steam. I think it's doing the same on CachyOS.

Without your theme enabled : 
![image](https://github.com/user-attachments/assets/c81d346a-0f4c-43ff-8ba6-345deacd236d)

With your theme enabled : 
![image](https://github.com/user-attachments/assets/4d3c9c4f-3169-423b-aa81-0a54ed80d306)

**Comment by victor-borges** [comment]
This is intended, because that slider does nothing in Bazzite (see #4) and is handled by HHD

**Comment by SeeDborg** [comment]
Maybe an option to hide it or not, then ?
Maybe they'll add the option in the future...

And when it's hidden, there is a bug, the option is still there, but "invisible" : 
https://github.com/user-attachments/assets/0948b030-e3d8-41f9-90ed-8b5cf7499f4a

**Comment by victor-borges** [comment]
It should be OK and not allow selection now! I'm not keen on adding an option for this because that slider is non-functional, this theme also hides some other non-functioning controls depending on the theme selected (like trackpad, gyro, some back buttons etc.)
