### ISSUE TITLE
Add support for "Steam Controller (HHD)"

### ISSUE THREAD

**Issue by eduardlleshi** [victor-borges/handheld-controller-glyphs#8]
With a recent update, Handheld Daemon added a "Steam Controller" option and the devs are suggesting using that going forward. 

I'm using the Rog Ally theme and only the face buttons are showing the right buttons, the rest is showing as generic buttons including the controller image.

**Comment by victor-borges** [comment]
Done! If you're using Bazzite then it should pull the changes when updating (can trigger it early with the System Upgrade tool in Desktop Mode), if installed through the Deck Themes store then it will take a bit because it's waiting on approval.
